version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:4442"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4442/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./server/data:/app/data
      - ./server/logs:/app/logs
    env_file:
      - server/.env
    environment:
      - NODE_ENV=production
      - PORT=3010
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  server_data:
    driver: local
  server_logs:
    driver: local