FROM node:20-alpine

RUN apk add --no-cache git

WORKDIR /app

COPY package*.json ./
RUN yarn install
RUN yarn add webpack@latest webpack-cli@latest

COPY . .

RUN npx webpack --mode production

EXPOSE 4442

CMD ["yarn", "serve"]